[window]
decorations = "Full"
startup_mode = "Maximized"
opacity = 0.9
blur = true
dynamic_title = false
title = ""
decorations_theme_variant = "Dark"

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
normal.style = "Thin"
size = 18
